services:
  mysql:
    image: mysql:8.0
    container_name: expense_sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expende_manager
      MYSQL_USER: Nerhon
      MYSQL_PASSWORD: ExpenseNerhon
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: