services:
  mysql:
    image: mysql:8.0
    container_name: expense_sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expende_manager
      MYSQL_USER: Nerhon
      MYSQL_PASSWORD: ExpenseNerhon
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_data
    restart: always
    ports:
      - "6379:6379"
volumes:
  mysql_data:
  redis_data:

